palette:
  top: '#4a4a4a'
  bottom: '#4e4e4e'
  bg: '#ffffff'
  sidebar: '#ffffff'
  sidebarborders: '#d0d0d0'
  footer: '#0c9fb9'
  titleslogan: '#ffffff'
  text: '#3b3b3b'
  link: '#0073b6'
logo: 'public://color/bartik-e9ed21ae/logo.svg'
stylesheets:
  - 'public://color/bartik-e9ed21ae/colors.css'
files:
  - 'public://color/bartik-e9ed21ae/logo.svg'
  - 'public://color/bartik-e9ed21ae/colors.css'
